# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
