# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransactions',
            name='quantity_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
