# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210818_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransactions',
            name='batch_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorytransactions',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='OUT', max_length=32),
        ),
    ]
