# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_supplieradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AGENT', 'AGENT'), ('COOPERATIVE', 'COOPERATIVE')], max_length=64)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('PERCENT', 'PERCENT'), ('AMOUNT', 'AMOUNT')], max_length=64)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Supplier')),
            ],
            options={
                'db_table': 'sale_commission',
            },
        ),
    ]
