# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-13 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_salescommission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salescommission',
            unique_together=set([('supplier', 'category')]),
        ),
    ]
