# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210713_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
