# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-17 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210713_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
