# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210717_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAdditionalCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('charge_type', models.CharField(choices=[('CHARGE', 'CHARGE'), ('DISCOUNT', 'DISCOUNT')], max_length=36)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_type', models.CharField(choices=[('AMOUNT', 'AMOUNT'), ('PERCENTAGE', 'PERCENTAGE')], max_length=36)),
            ],
            options={
                'db_table': 'item_addition_charges',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='allow_loan_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supplier/logo/'),
        ),
    ]
