# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210729_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='category_code',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
