# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210730_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
