# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-31 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210730_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ItemCategory'),
        ),
    ]
