# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-31 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_itemcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
    ]
