# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-15 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditmanager',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
