# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20210715_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='reference',
            field=models.CharField(default=b'', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
