# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_loanrequest_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
