# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-16 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_loantransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.LoanRequest'),
        ),
    ]
