# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_auto_20210818_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coop.Cooperative'),
        ),
    ]
