# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0011_cooperativemember_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorder',
            name='request_type',
            field=models.CharField(choices=[['LOAN', 'LOAN'], ['CASH', 'CASH'], ['MOBILE_MONEY', 'MOBILE_MONEY']], default=b'CASH', max_length=120),
            preserve_default=False,
        ),
    ]
