# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-13 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0014_auto_20210713_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
