# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0015_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
