# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-13 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0016_auto_20210714_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=255, null=True),
        ),
    ]
