# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-15 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coop', '0018_auto_20210714_2346'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Transaction',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('transaction_reference', models.CharField(max_length=160)),
        #         ('transaction_category', models.CharField(max_length=120)),
        #         ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
        #         ('entry_type', models.CharField(blank=True, max_length=64, null=True)),
        #         ('created_by_name', models.CharField(blank=True, max_length=160, null=True)),
        #         ('create_date', models.DateTimeField(auto_now_add=True)),
        #         ('update_date', models.DateTimeField(auto_now=True)),
        #         ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user', to=settings.AUTH_USER_MODEL)),
        #         ('members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember')),
        #         ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'db_table': 'transaction',
        #     },
        # ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='member',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='members',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoanRequest',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
