# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0019_auto_20210715_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
