# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-17 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0021_auto_20210717_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='members',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
