# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0025_auto_20210717_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativemember',
            name='cotton_acreage',
        ),
        migrations.RemoveField(
            model_name='cooperativemember',
            name='soghum_acreage',
        ),
        migrations.RemoveField(
            model_name='cooperativemember',
            name='soya_beans_acreage',
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='is_handicap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='id_number',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
