# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-18 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='coop_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember'),
        ),
        migrations.AddField(
            model_name='visit',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='coop_member',
            field=models.ManyToManyField(blank=True, to='coop.CooperativeMember'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='external_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.ExternalTrainer'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='thematic_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.ThematicArea'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='thematic_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ThematicArea'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='coop_member',
            field=models.ManyToManyField(blank=True, to='coop.CooperativeMember'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='training_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.TrainingModule'),
        ),
    ]
