# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-18 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_auto_20210818_2134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_auto_20210818_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('coop_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember')),
            ],
            options={
                'db_table': 'soil_test',
            },
        ),
        migrations.CreateModel(
            name='SoilTestSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=120)),
                ('measure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('soil_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.SoilTest')),
            ],
            options={
                'db_table': 'soil_test_sample',
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_item',
            },
        ),
        migrations.AddField(
            model_name='soiltestsample',
            name='test_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.TestItem'),
        ),
    ]
